name: quantum-portfolio-2024
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - qiskit==1.1.1
    - qiskit-aer==0.14.2
    - qiskit-optimization==0.6.1
    - dwave-ocean-sdk==7.1.0
    - dimod==0.12.16
    - yfinance==0.2.50
    - pandas==2.2.2
    - numpy==1.26.4
    - gurobipy==11.0.1
    - matplotlib==3.8.4
    - jupyter==1.0.0
    - notebook==7.1.3
    - ipykernel==6.29.4
